databases:
  - name: illumi-diary-db
    databaseName: illumi_diary_db
    user: illumi-diary-app
    region: singapore

services:
  - type: web
    name: illumi-diary-app
    runtime: ruby
    region: singapore
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: illumi-diary-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false