databases:
  - name: illumi-diary-db
    databaseName: illumi-diary-db
    user: illumi_diary_db_user
    region: singapore

services:
  - type: web
    name: illumi-diary-app
    region: singapore
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: illumi-diary-db
          property: connectionString